# Generated by Django 3.1 on 2020-08-11 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='+23491234567', max_length=50),
        ),
        migrations.CreateModel(
            name='ProofOfPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=100)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.investmentplan')),
            ],
        ),
    ]
