# Generated by Django 3.1 on 2020-09-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20200823_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proofofpayment',
            name='file',
            field=models.FileField(upload_to='files/pop/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
