# Generated by Django 3.1 on 2020-09-04 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20200904_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bank_account_number',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
