# Generated by Django 3.1 on 2020-09-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20200904_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
