# Generated by Django 3.1 on 2020-09-04 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0008_auto_20200904_1123'),
        ('dashboard', '0013_auto_20200904_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proofofpayment',
            name='investment',
        ),
        migrations.AddField(
            model_name='proofofpayment',
            name='investment_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainsite.investmentplan'),
        ),
    ]
