# Generated by Django 3.1 on 2020-09-04 11:26

import dashboard.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0008_auto_20200904_1123'),
        ('dashboard', '0014_auto_20200904_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proofofpayment',
            name='investment_plan',
            field=models.ForeignKey(default=dashboard.models.ProofOfPayment.get_default_plan, on_delete=django.db.models.deletion.DO_NOTHING, to='mainsite.investmentplan'),
        ),
    ]
