# Generated by Django 3.1 on 2020-09-04 11:55

import dashboard.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20200904_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='proofofpayment',
            name='user',
            field=models.ForeignKey(default=dashboard.models.ProofOfPayment.get_default_user, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.user'),
        ),
    ]
