# Generated by Django 3.1 on 2020-09-04 14:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_proofofpayment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='investment_plan',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='user',
        ),
        migrations.AddField(
            model_name='investment',
            name='pop',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.proofofpayment'),
        ),
        migrations.AddField(
            model_name='proofofpayment',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='investment',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Inactive')], default=False),
        ),
        migrations.AlterField(
            model_name='proofofpayment',
            name='is_valid',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Invalid'), (3, 'Valid')], default=1),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.FloatField()),
                ('Investment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.investment')),
            ],
        ),
    ]
