# Generated by Django 3.1 on 2020-09-04 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20200904_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='Investment',
            new_name='investment',
        ),
    ]
