# Generated by Django 3.1 on 2020-09-04 16:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20200904_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='proofofpayment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
