# Generated by Django 3.1 on 2020-09-06 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_proofofpayment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investment',
            old_name='pop',
            new_name='pop',
        ),
    ]
