# Generated by Django 3.1 on 2020-09-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.BooleanField(choices=[(True, 'Paid'), (False, 'Unpaid')], default=False),
        ),
    ]
