# Generated by Django 3.1 on 2020-09-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_auto_20200907_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.IntegerField(choices=[(1, 'Paid'), (2, 'Unpaid'), {3, 'Pending'}], default=2),
        ),
    ]
