# Generated by Django 3.1 on 2020-09-21 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_referral_referralpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referred',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='my_referrers', to='dashboard.user'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='my_referrals', to='dashboard.user'),
        ),
    ]
