# Generated by Django 3.1 on 2020-09-23 07:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_auto_20200921_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralpayment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
