# Generated by Django 3.1 on 2020-09-23 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_notification_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='time',
            new_name='datetime',
        ),
    ]
