# Generated by Django 3.1 on 2020-08-11 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_auto_20200811_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(help_text='description of plan with all needed detials')),
                ('roi', models.IntegerField(help_text='Return of investment in percentage')),
            ],
        ),
    ]
