# Generated by Django 3.1 on 2020-09-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0008_auto_20200904_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentplan',
            name='investment_duration',
            field=models.IntegerField(default=12, help_text='Duration of Investment in months'),
        ),
    ]
