# Generated by Django 3.1 on 2020-09-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0009_investmentplan_investment_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentplan',
            name='second_payment_date',
        ),
        migrations.AddField(
            model_name='investmentplan',
            name='second_payment_day',
            field=models.IntegerField(blank=True, choices=[(1, 'First day'), (2, 'Second day'), (3, 'Third day'), (4, 'Fourth day'), (5, 'Fifth day'), (6, 'Sixth day'), (7, 'Seventh day'), (8, 'Eight day'), (9, 'Ninth day'), (10, 'Tenth day'), (11, 'Eleventh day'), (12, 'Twelfth day'), (13, 'Thirteenth day'), (14, 'Fourteenth day'), (15, 'Fifteenth day'), (16, 'Sixteenth day'), (17, 'Seventeenth day'), (18, 'Eighteenth day'), (19, 'Nineteenth day'), (20, 'Twenteeth day'), (21, 'Twenty-first day'), (22, 'Twenty-second day'), (23, 'Twenty-third day'), (24, 'Twenty-fourth day'), (25, 'Twenty-fifth day'), (26, 'Twenty-sixth day'), (27, 'Twenty-seventh day'), (28, 'Twenty-eight day'), (29, 'Twenty-ninth day'), (30, 'Thirtieth day'), (31, 'Thirty-first day')], help_text='Day in the month for the second payment', null=True),
        ),
        migrations.AlterField(
            model_name='investmentplan',
            name='first_payment_day',
            field=models.IntegerField(blank=True, choices=[(1, 'First day'), (2, 'Second day'), (3, 'Third day'), (4, 'Fourth day'), (5, 'Fifth day'), (6, 'Sixth day'), (7, 'Seventh day'), (8, 'Eight day'), (9, 'Ninth day'), (10, 'Tenth day'), (11, 'Eleventh day'), (12, 'Twelfth day'), (13, 'Thirteenth day'), (14, 'Fourteenth day'), (15, 'Fifteenth day'), (16, 'Sixteenth day'), (17, 'Seventeenth day'), (18, 'Eighteenth day'), (19, 'Nineteenth day'), (20, 'Twenteeth day'), (21, 'Twenty-first day'), (22, 'Twenty-second day'), (23, 'Twenty-third day'), (24, 'Twenty-fourth day'), (25, 'Twenty-fifth day'), (26, 'Twenty-sixth day'), (27, 'Twenty-seventh day'), (28, 'Twenty-eight day'), (29, 'Twenty-ninth day'), (30, 'Thirtieth day'), (31, 'Thirty-first day')], help_text='Day in the month for the first payment', null=True),
        ),
    ]
