# Generated by Django 3.1 on 2020-09-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0011_auto_20200907_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentplan',
            name='description',
            field=models.TextField(help_text='description of plan with all needed detials including duration and anything the client needs to know about the plan'),
        ),
    ]
