# Generated by Django 3.1 on 2020-09-21 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_auto_20200921_1206'),
        ('mainsite', '0012_auto_20200908_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationlink',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.user'),
        ),
    ]
