# Generated by Django 3.1.2 on 2020-12-06 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0013_auto_20200921_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentplan',
            name='first_payment_day',
        ),
        migrations.RemoveField(
            model_name='investmentplan',
            name='second_payment_date',
        ),
    ]
